lsi: false
safe: true
source: edinburghindiegamers
timezone: Europe/London
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: jekyll/minima
