lsi: false
safe: true
source: edinburghindiegamers
title: "Edinburgh Indie Gamers"
timezone: Europe/London
author:
  name: "James Harding"
  email: "james@james-t-harding.com"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: jekyll/minima
permalink: /:categories/:year/:month/:day/:slug:output_ext
